baseURL: "https://srinivasanant.com"
title: Srinivas Anant
paginate: 5
theme: PaperMod
enableInlineShortcodes: true

params:
  author: Srinivas Anant
  description: "Personal Blog"
  keywords: [Blog, Portfolio]
  ShowReadingTime: true
  enableEmoji: true
  displayFullLangName: true
  ShowCodeCopyButtons: true
  disableScrollToTop: false
  enableGoogleAnalytics: false
  disableThemeToggle: true

  profileMode:
    enabled: false
    title: "Hello Friend!" # optional default will be site title
    subtitle: "We`` blog!"
    imageUrl: "https://twemoji.maxcdn.com/v/latest/svg/1f977.svg" # optional
    imageWidth: 600 # custom size
    imageHeight: 100 # custom size
    

menu:
  main:
    - identifier: tags
      name: Tags
      url: tags/
      weight: 10
    - identifier: projects
      name: Projects
      url: projects/
      weight: 20
    - identifier: about
      name: About
      url: about/
      weight: 30
    - identifier: archives
      name: Archives
      url: archives/
      weight: 40